pipeline {
    agent { label 'mesos' }
    environment {
        PLAYBOOK='prm/owca/workloads/run_workloads.yaml'
        INVENTORY='prm/demo_scenarios/common/inventory.yaml'
        LLC_INVENTORY='prm/demo_scenarios/complex_llc.0/inventory.yaml'
        MEMBW_INVENTORY='prm/demo_scenarios/complex_mbw.0/inventory.yaml'
        PROMETHEUS='http://100.64.176.12:9090' 
        MESOS_MASTER_HOST='100.64.176.23'
        BASELINE_SLEEP = 240
        CONTENDER_SLEEP = 240
        BUILD_COMMIT = "${GIT_COMMIT}"
    }
    options {
        disableConcurrentBuilds()
        timeout(time: 25, unit: 'MINUTES')
    }
    parameters {
        booleanParam(name: 'BUILD_PEX', defaultValue: true, description: 'Build owca-pex')
        booleanParam(name: 'LLC', defaultValue: true, description: 'Run LLC experiment')
        booleanParam(name: 'MB', defaultValue: true, description: 'Run MBW experiment')
    }
    stages {
        stage('Build pex') {
            when { expression { return params.BUILD_PEX } }
            stages {
                stage("Prepare venv && build pex") {
                    steps {
                        dir('prm') {
                            sh('make venv')
                            sh('make check')
                            sh('make package')
                        }
                    }
                }
            }
        }
        stage("Prepare aurora cluster") {
            when { expression { return params.MB | params.LLC} }
            steps {
                sh'''
                mkdir -p ${HOME}/.aurora
                cp ${WORKSPACE}/prm/demo_scenarios/common/aurora-clusters.json  ${HOME}/.aurora/clusters.json
                '''
            }
        }
        stage("Run LLC experiment") {
            when { expression { return params.LLC } }
            environment {
                MESOS_EXPECTED_TASKS = -1
                MIN_RECALL = -1
                MIN_PRECISION = -1
                BUILD_SCENARIO = "llc"
                LABELS="{additional_labels: {build_number: \"${BUILD_NUMBER}\", build_node_name: \"${NODE_NAME}\", build_commit: \"${GIT_COMMIT}\", build_scenario: \"$BUILD_SCENARIO\"}}"
            }
            steps {
                echo 'Reconfigure owca...'
                contentReplace(
                    configs: [
                        fileContentReplaceConfig(
                            configs: [
                                fileContentReplaceItemConfig( search: 'BUILD_COMMIT', replace: "${GIT_COMMIT}", matchCount: 0),
                                fileContentReplaceItemConfig( search: 'BUILD_NUMBER', replace: "${BUILD_NUMBER}", matchCount: 0),
                                fileContentReplaceItemConfig( search: 'BUILD_SCENARIO', replace: "${BUILD_SCENARIO}", matchCount: 0)
                            ],
                            fileEncoding: 'UTF-8', 
                            filePath: "${WORKSPACE}/prm/demo_scenarios/common/owca_config.yml")
                        ])
                sh'''
                sudo cp ${WORKSPACE}/prm/demo_scenarios/common/threshold.json /var/lib/owca/
                sudo cp ${WORKSPACE}/prm/demo_scenarios/common/workload.json /var/lib/owca/
                sudo cp ${WORKSPACE}/prm/demo_scenarios/common/owca_config.yml /etc/owca/
                sudo cp ${WORKSPACE}/prm/dist/owca-prm.pex /usr/bin/
                sudo systemctl restart owca
                '''
                echo 'Restart owca...'
                sleep 5
                sh 'sudo systemctl status owca'

                dir('prm/owca/workloads'){
                    echo 'Start baseline workloads.'
                    sh 'ansible-playbook -vvv -i ${WORKSPACE}/${LLC_INVENTORY} -i ${WORKSPACE}/${INVENTORY} --tags=twemcache_mutilate,redis_rpc_perf,cassandra_stress--cassandra -e "${LABELS}" ${WORKSPACE}/${PLAYBOOK}'
                    sleep BASELINE_SLEEP
                    echo 'Start contender workload.'
                    sh 'ansible-playbook -vvv -i ${WORKSPACE}/${LLC_INVENTORY} -i ${WORKSPACE}/${INVENTORY} --tags=cassandra_stress--stress -e "${LABELS}" ${WORKSPACE}/${PLAYBOOK}'
                    sleep CONTENDER_SLEEP
                }
                dir('prm'){
                    echo 'Calculate precision and recall...'
                    sh "PYTHONPATH=. pipenv run pytest tests/e2e/test_calculate_accuracy.py --junitxml=unit_results.xml --junit-prefix=${BUILD_SCENARIO} --log-level=debug --log-cli-level=debug -v"
                }
            }
            post {
                always {
                    echo 'Stop all workloads...'
                    sh 'ansible-playbook -v -i ${WORKSPACE}/${INVENTORY} --tags=clean_jobs ${WORKSPACE}/${PLAYBOOK}'
                    sleep 5
                    echo 'Plot LLC results...'
                    plot(
                        csvFileName: 'llc_results.csv',
                        style: 'line',
                        csvSeries: [
                            [
                                displayTableFlag: false,
                                exclusionValues: '',
                                inclusionFlag: 'OFF',
                                file: 'prm/test_results.csv',
                                url: ''
                            ]
                        ],
                       group: 'PRM performance v4',
                       title: 'LLC complex scenario',
                       numBuilds: '5',
                    )
                    echo 'Storing LLC results.'
                    junit 'prm/unit_results.xml'
                    echo 'Stop owca...'
                    sh 'sudo systemctl stop owca'
                }
            }
        }
        stage("Run Memory Bandwidth experiment") {
            when {
                expression { return params.MB }
            }
            environment {
                MESOS_EXPECTED_TASKS = -1
                MIN_RECALL = -1
                MIN_PRECISION = -1
                BUILD_SCENARIO = "mbw"
                LABELS="{additional_labels: {build_number: \"${BUILD_NUMBER}\", build_node_name: \"${NODE_NAME}\", build_commit: \"${GIT_COMMIT}\", build_scenario: \"$BUILD_SCENARIO\"}}"
            }


            steps {

                echo 'Reconfigure owca...'
                contentReplace(
                    configs: [
                        fileContentReplaceConfig(
                            configs: [
                                fileContentReplaceItemConfig( search: 'BUILD_COMMIT', replace: "${GIT_COMMIT}", matchCount: 0),
                                fileContentReplaceItemConfig( search: 'BUILD_NUMBER', replace: "${BUILD_NUMBER}", matchCount: 0),
                                fileContentReplaceItemConfig( search: 'BUILD_SCENARIO', replace: "${BUILD_SCENARIO}", matchCount: 0)
                            ],
                            fileEncoding: 'UTF-8', 
                            filePath: "${WORKSPACE}/prm/demo_scenarios/common/owca_config.yml")
                        ])
                sh'''
                sudo cp ${WORKSPACE}/prm/demo_scenarios/common/threshold.json /var/lib/owca/
                sudo cp ${WORKSPACE}/prm/demo_scenarios/common/workload.json /var/lib/owca/
                sudo cp ${WORKSPACE}/prm/demo_scenarios/common/owca_config.yml /etc/owca/
                sudo cp ${WORKSPACE}/prm/dist/owca-prm.pex /usr/bin/
                sudo systemctl restart owca
                '''
                sleep 5
                echo 'Restart owca...'
                sh 'sudo systemctl status owca'

                dir('prm/owca/workloads'){
                    echo 'Start baseline workloads.'
                    sh 'ansible-playbook -vvv -i ${WORKSPACE}/${MEMBW_INVENTORY} -i ${WORKSPACE}/${INVENTORY} --tags=specjbb,tensorflow_benchmark_prediction,tensorflow_benchmark_train,cassandra_stress -e "${LABELS}" ${WORKSPACE}/${PLAYBOOK}' 
                    sleep BASELINE_SLEEP
                    echo 'Start contender workload.'
                    sh 'ansible-playbook -vvv -i ${WORKSPACE}/${MEMBW_INVENTORY} -i ${WORKSPACE}/${INVENTORY} --tags=tensorflow_benchmark_prediction -e "${LABELS}" ${WORKSPACE}/${PLAYBOOK}'
                    sleep CONTENDER_SLEEP
                }
                dir('prm'){
                    echo 'Calculate precision and recall...'
                    sh "PYTHONPATH=. pipenv run pytest tests/e2e/test_calculate_accuracy.py --junitxml=unit_results.xml --junit-prefix=${BUILD_SCENARIO} --log-level=debug --log-cli-level=debug -v"
                }
            }
            post {
                always {
                    echo 'Stop all workloads...'
                    sh 'ansible-playbook -v -i ${WORKSPACE}/${INVENTORY} --tags=clean_jobs ${WORKSPACE}/${PLAYBOOK}'
                    sleep 5
                    echo 'Plot LLC results...'
                    plot(
                        csvFileName: 'mbw_results.csv',
                        style: 'line',
                        csvSeries: [
                            [
                                displayTableFlag: false,
                                exclusionValues: '',
                                inclusionFlag: 'OFF',
                                file: 'prm/test_results.csv',
                                url: ''
                            ]
                        ],
                       group: 'PRM performance v4',
                       title: 'MBW complex scenario',
                       numBuilds: '5',
                    )
                    echo 'Storing MBW results.'
                    junit 'prm/unit_results.xml'
                    echo 'Stop owca...'
                    sh 'sudo systemctl stop owca'
                }
            }
        }
    }
}
