pipeline {
    agent any
    stages {
        stage("Run flake8 on PRM") {
            steps {
                sh'''
                cd prm
                tox -e flake8
                '''
            }
        }
        stage("Build owca-prm.pex") {
            steps {
                sh'''
                cd prm
                tox -e package
                '''
                stash(name: "wrappers", includes: "prm/dist/**")
                archiveArtifacts(artifacts: "prm/dist/**")
            }
            post {
                always {
                    sh '''
                    rm -fr prm/dist
                    '''
                }
            }
        }
    }
}
