runner: !AllocationRunner
  rdt_enabled: True
  node: !MesosNode
    mesos_agent_endpoint: "http://127.0.0.1:5051"
  action_delay: &action_delay 1.
  metrics_storage: !LogStorage
    output_filename: /tmp/metrics.log
  anomalies_storage: !LogStorage
    output_filename: /tmp/anomalies.log
  allocations_storage: !LogStorage
    output_filename: /tmp/allocations.log
  allocator: !ResourceAllocator
    action_delay: *action_delay
    mode_config: 'detect'
    agg_period: 20.
    exclusive_cat: False
     
  extra_labels:
    env_uniq_id: "15"
    own_ip: "100.64.176.15"
